services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////app/mlflow.db
      - --artifacts-destination
      - /app/mlartifacts
      - --allowed-hosts
      - "mlflow:5000,mlflow,localhost:*,127.0.0.1:*"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow